security:
    oauth2:
        client:
            clientId: 926367192509-e9463s7o99gsarv6ovn7lcnberpots0e.apps.googleusercontent.com
            clientSecret: E8wgA8VSZjVEjnmGSgvxW_M8
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false